server:
  port: 8082

spring:
  application:
    name: tracker-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

backend:
  service:
    pesonUrl: http://finance-data-service