server:
  port: 8083

spring:
  application:
    name: finance-data-service

  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8081
  instance:
    preferIpAddress: true
com:
  mps:
    finance:
      jpa:
        repo:
          enabled: true