server:
  port: 8083

spring:
  application:
    name: finance-data-service

  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      generate-ddl: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    logging:
      level:
        org:
          hibernate:
            type: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    preferIpAddress: true

com:
  mps:
    finance:
      jpa:
        repo:
          enabled: true