server:
  port: 8082

spring:
  application:
    name: finance-tracker-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

person:
  data:
    service:
      url: http://finance-data-service

    feign:
      client:
        enabled: true